version: "3.7"

services: 
    node:
        image: node:16-alpine
        restart: 'no'
        ports: [8080:8080]
        volumes: [.:/srv/app]
        working_dir: /srv/app
        command: yarn run serve
